import turtle
t = turtle.Turtle()
t.speed(500)
t.penup()
t.goto(-50,-50)
t.pendown()
t.color("#FFDE33")
t.fillcolor("#FFDE33")
t.begin_fill()
for count in range(4):
    t.forward(100)
    for count in range(90):
        t.left(1)
        t.forward(1)
t.end_fill()

t.penup()
t.goto(-40,-40)
t.pendown()
t.color("#FF6033")
t.fillcolor("#FF6033")
t.begin_fill()
for count in range(2):
    t.forward(80)
    for count in range(90):
        t.left(1)
        t.forward(1)
t.forward(80)
t.left(90)
for count in range(90):
    t.right(1)
    t.forward(1)
t.left(90)
t.forward(80)
for count in range(90):
    t.left(1)
    t.forward(1)
t.forward(1)
t.end_fill()

t.penup()
t.goto(-35,-35)
t.pendown()
t.color("#245887")
t.fillcolor("#245887")
t.begin_fill()
for count in range(2):
    t.forward(70)
    for count in range(90):
        t.left(1)
        t.forward(1)
t.forward(70)
t.left(90)
for count in range(90):
    t.right(1)
    t.forward(1)
t.left(90)
t.forward(70)
for count in range(90):
    t.left(1)
    t.forward(1)
t.forward(1)
t.end_fill()

t.color("#000000","#FFDE33")
t.pensize(4)
t.penup()
t.goto(90,70)
t.pendown()
t.left(135)
t.begin_fill()
for count in range(4):
    t.forward(110)
    t.left(90)
t.end_fill()

t.fillcolor("#6DE9E5")
t.penup()
t.left(90)
t.forward(20)
t.right(90)
t.forward(40)
t.pendown()
t.begin_fill()
for count in range(2):
    t.forward(15)
    t.left(90)
    t.forward(70)
    t.left(90)
t.end_fill()

t.penup()
t.forward(15)
t.left(90)
t.forward(5)
t.right(90)
t.forward(15)
t.pendown()
t.begin_fill()
for count in range(4):
    t.forward(20)
    t.left(90)
t.end_fill()

t.penup()
t.left(90)
t.forward(40)
t.right(90)
t.pendown()
t.begin_fill()
for count in range(4):
    t.forward(20)
    t.left(90)
t.end_fill()

t.color("#FFFFFF","#FFFFFF")
t.pensize(1)
t.penup()
t.goto(90,70)
t.left(90)
t.forward(110)
t.left(135)
t.pendown()
t.forward(70)
t.backward(160)
t.fillcolor("#000000")
t.begin_fill()
t.left(65)
t.forward(50)
t.right(130)
t.forward(50)
t.end_fill()
